euskalbar.dicts.menu = [
  { cat: "General",
    dicts: [
      { name: 'Hiztegi Batua',
        url: 'http://www.euskaltzaindia.net/hiztegibatua' },
      { name: 'Orotariko Euskal Hiztegia',
        url: 'http://www.euskaltzaindia.net/oeh' },
      { sep: true },
      { name: 'Euskalterm Terminological Bank',
        url: 'http://www1.euskadi.net/euskalterm/indice_e.htm' },
      { name: '3000 Hiztegia',
        url: 'http://www1.euskadi.net/hizt_3000/indice_e.htm' },
      { name: 'Elhuyar Hiztegia',
        url: 'http://www.elhuyar.org/hizkuntza-zerbitzuak/EU/Hiztegi-kontsulta' },
      { name: 'Labayru Hiztegia',
        url: 'http://zerbitzuak.labayru.org/diccionario/hiztegiasarrera.asp' },
      { name: 'Zehazki Hiztegia',
        url: 'http://ehu.es/ehg/zehazki/' },
      { name: 'BFA Terminological Dictionary',
        url: 'http://aplijava.bizkaia.net/TK00/servlet/webAgentTK00' },
      { sep: true },
      { name: 'Morris dictionary',
        url: 'http://www1.euskadi.net/morris/indice_e.htm' },
      { name: 'Open-Tran translation database',
        url: 'http://eu.open-tran.eu' },
      { sep: true },
      { name: 'Polish - Basque dictionary',
        url: 'http://www.hiztegia.org' },
      { name: 'Goihata dictionary',
        url: 'http://www.goihata.com/eu/japoniera-hiztegia/' }
    ]
  },
  { cat: 'Synonyms',
    dicts: [
      { name: 'Adorez synonyms dictionary',
        url: 'http://www1.euskadi.net/hizt_sinon/indice_e.htm' },
      { name: 'UZEI synonyms dictionary',
        url: 'http://www.uzei.com/estatico/sinonimos.asp' },
      { name: 'Eurovoc Thesaurus',
        url: 'http://www.bizkaia.net/kultura/eurovoc/index.asp' }
    ]
  },
  { cat: 'Encyclopedias',
    dicts: [
      { name: 'Auñamendi',
        url: 'http://www.euskomedia.org/euskomedia/SAunamendi?idi=eu&op=1' },
      { name: 'Wikipedia-eu',
        url: 'https://secure.wikimedia.org/wikipedia/eu/wiki/' },
      { name: 'Encyclopedic dictionary of Science and Technology',
        url: 'http://zthiztegia.elhuyar.org' }
    ]
  },
  { cat: 'By Subject',
    dicts: [
      { name: 'Drugs',
        url: 'http://www.drogomedia.com/eus/diccionario.php' },
      { name: 'Energy',
        url: 'http://www.eve.es/energia/index.html' },
      { name: 'Industry',
        url: 'http://www.kondia.com/hiztegi/home.htm' },
      { name: 'Industry (for immigrants)',
        url: 'http://clientes.incress.com:9080/imh/diccionario_entorno/' },
      { name: 'Computing',
        url: 'http://www.eionet.europa.eu/gemet/index_html?langcode=eu' },
      { name: 'Justice',
        url: 'http://www.justizia.net/uzei/idazki/lexiko/lexikoa.htm' },
      { name: 'Cataloguing',
        url: 'http://joana-albret.iametza.com' },
      { name: 'Parliament',
        url: 'http://parlamento.euskadi.net/pfrm_cm_hiztegie.html' },
      { name: 'Cooking',
        url: 'http://www.bagera.net/Bageranet/Ziberteka/Gastronomia/Sukaldehiztegia' },
      { name: 'Telecommunications',
        url: 'http://www.telekomunikaziohiztegia.org' },
    ]
  },
  { cat: 'Towns',
    dicts: [
      { name: 'Bergara zone dictionary',
        url: 'http://www.bergarakoeuskara.net/hiztegia' },
      { name: 'Eibarko euskeria',
        url: 'http://www.eibarko-euskara.com' }
    ]
  },
  { cat: 'Corpus',
    dicts: [
      { name: 'Mokoroa',
        url: 'http://hiru.com/hiztegiak/mokoroa' },
      { name: 'Intza',
        url: 'http://intza.armiarma.com/cgi-bin/bilatu2.pl' },
      { name: 'Gotzon Garate',
        url: 'http://www.ametza.com/bbk/htdocs/garate.htm' },
      { name: 'Basque Corpus',
        url: 'http://euskaracorpusa.net' },
      { name: 'Ereduzko prosa',
        url: 'http://www.ehu.es/euskara-orria/euskara/ereduzkoa/araka.html' },
      { name: 'Klasikoen gordailua',
        url: 'http://klasikoak.armiarma.com/corpus.htm' },
      { name: 'ZT Corpusa',
        url: 'http://ztcorpusa.net' },
      { name: 'Lexikoaren Behatokia',
        url: 'http://lexikoarenbehatokia.euskaltzaindia.net' },
      { name: 'Consumer Corpusa',
        url: 'http://corpus.consumer.es/corpus/' },
      { name: 'CorpEus',
        url: 'http://corpeus.org' },
    ]
  },
  { cat: 'Search Engines',
    dicts: [
      { name: 'Elebila',
        url: 'http://elebila.eu' }
    ]
  },
];
