euskalbar.dicts.menu = [
  { cat: "Orokorra",
    dicts: [
      { name: 'Euskaltzaindia',
        url: 'http://www.euskaltzaindia.net' },
      { name: 'Orotariko Euskal Hiztegia',
        url: 'http://www.euskaltzaindia.net/oeh' },
      { sep: true },
      { name: 'Euskalterm banku terminologikoa (eu-es)',
        url: 'http://www1.euskadi.net/euskalterm/indice_e.htm' },
      { name: '3000 hiztegia (eu-es)',
        url: 'http://www1.euskadi.net/hizt_3000/indice_e.htm' },
      { name: 'Elhuyar hiztegia (eu-es)',
        url: 'http://www.elhuyar.org/hizkuntza-zerbitzuak/EU/Hiztegi-kontsulta' },
      { name: 'Labayru hiztegia (eu-es)',
        url: 'http://zerbitzuak.labayru.org/diccionario/hiztegiasarrera.asp' },
      { name: 'Zehazki hiztegia (es-eu)',
        url: 'http://ehu.es/ehg/zehazki/' },
      { name: 'BFA Hiztegi Terminologikoa (eu-es)',
        url: 'http://aplijava.bizkaia.net/TK00/servlet/webAgentTK00' },
      { sep: true },
      { name: 'Morris hiztegia (eu-en)',
        url: 'http://www1.euskadi.net/morris/indice_e.htm' },
      { name: 'Open-Tran itzulpen datu-basea (en-eu)',
        url: 'http://eu.open-tran.eu' },
      { sep: true },
      { name: 'Poloniera - Euskara hiztegia (pl-eu)',
        url: 'http://www.hiztegia.org' },
      { name: 'Goihata hiztegia',
        url: 'http://www.goihata.com/eu/japoniera-hiztegia/' }
    ]
  },
  { cat: 'Sinonimoak',
    dicts: [
      { name: 'Adorez sinonimoen hiztegia',
        url: 'http://www1.euskadi.net/hizt_sinon/indice_e.htm' },
      { name: 'UZEIren sinonimoen hiztegia',
        url: 'http://www.uzei.com/estatico/sinonimos.asp' },
      { name: 'Eurovoc Thesaurusa',
        url: 'http://www.bizkaia.net/kultura/eurovoc/index.asp' }
    ]
  },
  { cat: 'Entziklopediak',
    dicts: [
      { name: 'Auñamendi entziklopedia',
        url: 'http://www.euskomedia.org/euskomedia/SAunamendi?idi=eu&op=1' },
      { name: 'Wikipedia',
        url: 'https://secure.wikimedia.org/wikipedia/eu/wiki/' },
      { name: 'Zientzia eta Teknologiaren Hiztegi Entziklopedikoa',
        url: 'http://zthiztegia.elhuyar.org' }
    ]
  },
  { cat: 'Gaikakoak',
    dicts: [
      { name: 'Drogak',
        url: 'http://www.drogomedia.com/eus/diccionario.php' },
      { name: 'Energia',
        url: 'http://www.eve.es/energia/index.html' },
      { name: 'Industria',
        url: 'http://www.kondia.com/hiztegi/home.htm' },
      { name: 'Industria (etorkinentzat)',
        url: 'http://clientes.incress.com:9080/imh/diccionario_entorno/' },
      { name: 'Informatika',
        url: 'http://www.eionet.europa.eu/gemet/index_html?langcode=eu' },
      { name: 'Justizia',
        url: 'http://www.justizia.net/uzei/idazki/lexiko/lexikoa.htm' },
      { name: 'Katalogazioa',
        url: 'http://joana-albret.iametza.com' },
      { name: 'Parlamentua',
        url: 'http://parlamento.euskadi.net/pfrm_cm_hiztegie.html' },
      { name: 'Sukaldaritza',
        url: 'http://www.bagera.net/Bageranet/Ziberteka/Gastronomia/Sukaldehiztegia' },
      { name: 'Telekomunikazioak',
        url: 'http://www.telekomunikaziohiztegia.org' },
    ]
  },
  { cat: 'Herriak',
    dicts: [
      { name: 'Bergara aldeko hiztegia',
        url: 'http://www.bergarakoeuskara.net/hiztegia' },
      { name: 'Eibarko euskeria',
        url: 'http://www.eibarko-euskara.com' }
    ]
  },
  { cat: 'Corpusak',
    dicts: [
      { name: 'Mokoroa',
        url: 'http://hiru.com/hiztegiak/mokoroa' },
      { name: 'Intza',
        url: 'http://intza.armiarma.com/cgi-bin/bilatu2.pl' },
      { name: 'Gotzon Garate',
        url: 'http://www.ametza.com/bbk/htdocs/garate.htm' },
      { name: 'Euskararen Corpusa',
        url: 'http://euskaracorpusa.net' },
      { name: 'Ereduzko prosa',
        url: 'http://www.ehu.es/euskara-orria/euskara/ereduzkoa/araka.html' },
      { name: 'Klasikoen gordailua',
        url: 'http://klasikoak.armiarma.com/corpus.htm' },
      { name: 'ZT Corpusa',
        url: 'http://ztcorpusa.net' },
      { name: 'Lexikoaren Behatokia',
        url: 'http://lexikoarenbehatokia.euskaltzaindia.net' },
      { name: 'Consumer Corpusa',
        url: 'http://corpus.consumer.es/corpus/' },
      { name: 'CorpEus',
        url: 'http://corpeus.org' },
    ]
  },
  { cat: 'Bilatzaileak',
    dicts: [
      { name: 'Elebila',
        url: 'http://elebila.eu' }
    ]
  },
];
